
AN ERROR HAS OCCURRED [the index 'value' does not exist]

CALLSTACK
*FUNCTION [__main__()] testData/static_analyzer/w248_eq_get.nut line [5]

LOCALS
[o] TABLE
[foo] CLOSURE
[vargv] ARRAY
[this] NULL
